create table cuis (cui varchar(255) not null, preferred_name TEXT, primary key (cui));
create table definitions (definition_id bigserial not null, meaning TEXT, source_name varchar(255), cui varchar(255), primary key (definition_id));
create table relationships (relationship_id bigserial not null, rel_type varchar(255), cui1 varchar(255), cui2 varchar(255), primary key (relationship_id));
create table semantic_types (semantic_type_id bigserial not null, type TEXT, cui varchar(255), primary key (semantic_type_id));
create table synonyms (synonym_id bigserial not null, source_name varchar(255), term TEXT, cui varchar(255), primary key (synonym_id));
create table umls_terms (id bigint not null, cui varchar(255), definition varchar(255), primary key (id));
alter table if exists definitions add constraint FKr0oainnk4n1erbq7kkrdkfm2k foreign key (cui) references cuis;
alter table if exists relationships add constraint FKr4e9edqoikp46ly4vlyjg4829 foreign key (cui1) references cuis;
alter table if exists relationships add constraint FKm1x9mknbckke7ctw89318grgg foreign key (cui2) references cuis;
alter table if exists semantic_types add constraint FK54seyvlwf7en3rd6ti09imikd foreign key (cui) references cuis;
alter table if exists synonyms add constraint FKsl0f6e1lfsb3ob5cxtb34wcgg foreign key (cui) references cuis;
create table cuis (cui varchar(255) not null, preferred_name TEXT, primary key (cui));
create table definitions (definition_id bigserial not null, meaning TEXT, source_name varchar(255), cui varchar(255), primary key (definition_id));
create table relationships (relationship_id bigserial not null, rel_type varchar(255), cui1 varchar(255), cui2 varchar(255), primary key (relationship_id));
create table semantic_types (semantic_type_id bigserial not null, type TEXT, cui varchar(255), primary key (semantic_type_id));
create table synonyms (synonym_id bigserial not null, source_name varchar(255), term TEXT, cui varchar(255), primary key (synonym_id));
create table umls_terms (id bigint not null, cui varchar(255), definition varchar(255), primary key (id));
alter table if exists definitions add constraint FKr0oainnk4n1erbq7kkrdkfm2k foreign key (cui) references cuis;
alter table if exists relationships add constraint FKr4e9edqoikp46ly4vlyjg4829 foreign key (cui1) references cuis;
alter table if exists relationships add constraint FKm1x9mknbckke7ctw89318grgg foreign key (cui2) references cuis;
alter table if exists semantic_types add constraint FK54seyvlwf7en3rd6ti09imikd foreign key (cui) references cuis;
alter table if exists synonyms add constraint FKsl0f6e1lfsb3ob5cxtb34wcgg foreign key (cui) references cuis;
create table cuis (cui varchar(255) not null, preferred_name TEXT, primary key (cui));
create table definitions (definition_id bigserial not null, meaning TEXT, source_name varchar(255), cui varchar(255), primary key (definition_id));
create table relationships (relationship_id bigserial not null, rel_type varchar(255), cui1 varchar(255), cui2 varchar(255), primary key (relationship_id));
create table semantic_types (semantic_type_id bigserial not null, type TEXT, cui varchar(255), primary key (semantic_type_id));
create table synonyms (synonym_id bigserial not null, source_name varchar(255), term TEXT, cui varchar(255), primary key (synonym_id));
create table umls_terms (id bigint not null, cui varchar(255), definition varchar(255), primary key (id));
alter table if exists definitions add constraint FKr0oainnk4n1erbq7kkrdkfm2k foreign key (cui) references cuis;
alter table if exists relationships add constraint FKr4e9edqoikp46ly4vlyjg4829 foreign key (cui1) references cuis;
alter table if exists relationships add constraint FKm1x9mknbckke7ctw89318grgg foreign key (cui2) references cuis;
alter table if exists semantic_types add constraint FK54seyvlwf7en3rd6ti09imikd foreign key (cui) references cuis;
alter table if exists synonyms add constraint FKsl0f6e1lfsb3ob5cxtb34wcgg foreign key (cui) references cuis;
create table cuis (cui varchar(255) not null, preferred_name TEXT, primary key (cui));
create table definitions (definition_id bigserial not null, meaning TEXT, source_name varchar(255), cui varchar(255), primary key (definition_id));
create table relationships (relationship_id bigserial not null, rel_type varchar(255), cui1 varchar(255), cui2 varchar(255), primary key (relationship_id));
create table semantic_types (semantic_type_id bigserial not null, type TEXT, cui varchar(255), primary key (semantic_type_id));
create table synonyms (synonym_id bigserial not null, source_name varchar(255), term TEXT, cui varchar(255), primary key (synonym_id));
create table umls_terms (id bigint not null, cui varchar(255), definition varchar(255), primary key (id));
alter table if exists definitions add constraint FKr0oainnk4n1erbq7kkrdkfm2k foreign key (cui) references cuis;
alter table if exists relationships add constraint FKr4e9edqoikp46ly4vlyjg4829 foreign key (cui1) references cuis;
alter table if exists relationships add constraint FKm1x9mknbckke7ctw89318grgg foreign key (cui2) references cuis;
alter table if exists semantic_types add constraint FK54seyvlwf7en3rd6ti09imikd foreign key (cui) references cuis;
alter table if exists synonyms add constraint FKsl0f6e1lfsb3ob5cxtb34wcgg foreign key (cui) references cuis;
