= UMLS Search Boot 🍃🥾
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

toc::[]

== Getting Started

To get started with UMLS Search Boot, follow the steps below:

. Download MetaMapLite:
* Visit the https://lhncbc.nlm.nih.gov/ii/tools/MetaMap/run-locally/MetaMapLite.html[NLM MetaMapLite] page.
* Download `2022AB UMLS Level 0+4+9 DataSet` zip file.
* Extract the zip file.
* Locate the `metamaplite-_<version>_-standalone.jar` at `target` directory.
* Install MetaMapLite jar to local Maven repository.
+
[source, console]
----
# windows powershell請把\換成`或移除\並寫成一行
mvnw install:install-file \
    -Dfile=<path to metamaplite-version-standalone.jar> \
    -DgroupId=gov.nih.nlm.nls \
    -DartifactId=metamaplite \
    -Dversion=<version> \
    -Dpackaging=jar \
    -DgeneratePom=true
----

* Configure MetaMapLite directory:
** Locate the `src/main/resources/.env` file.
** Set the `MMLITE_DIR` variable to the path that contains the `public_mm_lite` directory. For example, `/home/user/metamaplite`. 
   
. Set up Environment Variables:
* Locate the `src/main/resources/.env` file.
* Review the provided `.env.example` file for detailed instructions on setting up the required environment variables.
* Make sure to configure the environment variables correctly based on your specific setup.

. Run the Application:
* Open a terminal or command prompt.
* Navigate to the project root directory.
* Execute the following command:
+
[source, console]
----
mvn spring-boot:run
----
* This command will start the application listening on http://localhost:8080 , your can change the port at .env file or application.properties.

== Testing

To test UMLS Search Boot, you have two options:

. Using IntelliJ IDEA:
* Open IntelliJ IDEA.
* Navigate to the `src/test/java` directory.
* Right-click on the directory and select "Run 'All Tests'".
* IntelliJ IDEA will execute all the tests and display the results.

. Using Maven:
* Open a terminal or command prompt.
* Navigate to the project root directory.
* Execute the following command:
+
[source, console]
----
mvn test
----
* Maven will run all the tests in the project and provide the test results.

== Build

Build JAR file
[source, console]
----
mvn install \
  -Pci \ <1>
  -Ddir=<output directory> \ <2>
  -DfinalName=server 
----
<1> Use profile called `ci`, see https://maven.apache.org/guides/introduction/introduction-to-profiles.html
<2> Without this line, it would export to `umls-search/server/target`

== Deployment

. Create service file.
+
[%linenums,text]
----
# At /home/umlssearch/.config/systemd/user/umls-search.service
[Unit]
Description=UMLS Search Service
After=network.target

[Service]
EnvironmentFile=/home/umlssearch/.env <1>
ExecStart=/usr/bin/java -jar /home/umlssearch/target/server.jar <2>
ExecStop=/bin/kill -15 $MAINPID <3>
SuccessExitStatus=143
Restart=always

[Install]
WantedBy=multi-user.target
----
<1> You can configure .env file here.
<1> Or you can change file path as your built jar path.
<3> See https://www.baeldung.com/linux/run-java-application-as-service.

. Place `metamaplite` folder into `/home/umlssearch/`.
. Run `loginctl enable-linger umlssearch`, more information see https://wiki.archlinux.org/title/systemd/User#Automatic_start-up_of_systemd_user_instances
. Run `systemctl --user daemon-reload`
. At `/home/umlssearch/.config/systemd/user/`, Run `systemctl --user enable --now umls-search`

=== Continuous Integration

We use https://www.drone.io/[Drone CI]. The configuration is defined in the `.drone.yml` file.
[source, yaml]
----
kind: pipeline
type: docker
name: umls-search-server

steps:
  - name: stop service
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      command_timeout: 2m
      script:
        - systemctl --user stop umls-search <.>

  - name: build
    image: maven:3.9.2-eclipse-temurin-17-alpine
    volumes:
      - name: metamaplite_data
        path: /tmp/metamaplite
      - name: metamaplite_jar
        path: /tmp/metamaplite.jar
      - name: target_path
        path: /var/umls-search
    environment:
      MMLITE_DIR: /tmp/metamaplite
    commands: <.>
      - mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=/tmp/metamaplite.jar
      - |
        mvn -f server/pom.xml install \
          -Pci \
          -Ddir=/var/umls-search \
          -DfinalName=server

  - name: start service
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      command_timeout: 2m
      script:
        - systemctl --user start umls-search <.>

volumes:
  - name: metamaplite_data
    host:
      path: /home/umlssearch/metamaplite <.>
  - name: metamaplite_jar
    host:
      path: /home/umlssearch/metamaplite-3.6.2rc8-standalone.jar <.>
  - name: target_path
    host:
      path: /home/umlssearch/target
----
<.> Stop service, prepare for update.
<.> Build JAR.
* Install metamaplite to https://www.baeldung.com/maven-local-repository[local .m2 repo].
* Build jar to https://docs.docker.com/storage/volumes/[volume] `/var/umls-search`.
<.> Start service.
<.> metamaplite JAR volume, the docker container can access the `/home/umlssearch/metamaplite` directory as `/tmp/metamaplite`.
<.> Same as above.

== API

=== Search Concept by CUI

Search for a concept using the Concept Unique Identifier (CUI).

- Endpoint: `/api/v1/concepts/{cui}`
- Method: GET
- Parameters: `cui` (required)
- Example: http://localhost:8080/api/v1/concepts/C5397597

==== Response:
- Status Code: 200 (OK)
- Response Format: JSON
- Example Response:

.Click to see response (very long)
[%collapsible]
====
[source, json]
----
{
  "cui": "C0948008",
  "preferredName": "Ischemic stroke",
  "definitions": [
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "meaning": "An acute episode of focal cerebral, spinal, or retinal dysfunction caused by infarction of brain tissue.",
      "sourceName": "NCI"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "meaning": "Stroke due to BRAIN ISCHEMIA resulting in interruption or reduction of blood flow to a part of the brain. When obstruction is due to a BLOOD CLOT formed within in a cerebral blood vessel it is a thrombotic stroke. When obstruction is formed elsewhere and moved to block a cerebral blood vessel (see CEREBRAL EMBOLISM) it is referred to as embolic stroke. Wake-up stroke refers to ischemic stroke occurring during sleep while cryptogenic stroke refers to ischemic stroke of unknown origin.",
      "sourceName": "MSH"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "meaning": "<p>A <a href=\"https://medlineplus.gov/stroke.html\">stroke</a> is a medical emergency. There are two types - ischemic and <a href=\"https://medlineplus.gov/hemorrhagicstroke.html\">hemorrhagic</a>. Ischemic stroke is the more common type. It is usually caused by a <a href=\"https://medlineplus.gov/bloodclots.html\">blood clot</a> that blocks or plugs a blood vessel in the brain. This keeps blood from flowing to the brain. Within minutes, brain cells begin to die. Another cause is stenosis, or narrowing of the artery. This can happen because of <a href=\"https://medlineplus.gov/atherosclerosis.html\">atherosclerosis</a>, a disease in which plaque builds up inside your arteries. <a href=\"https://medlineplus.gov/transientischemicattack.html\">Transient ischemic attacks</a> (TIAs) occur when the blood supply to the brain is interrupted briefly. Having a TIA can mean you are at risk for having a more serious stroke.</p> <p>Symptoms of stroke are</p> <ul> <li>Sudden numbness or weakness of the face, arm or leg (especially on one side of the body)</li> <li>Sudden confusion, trouble speaking or understanding speech</li> <li>Sudden trouble seeing in one or both eyes</li> <li>Sudden trouble walking, dizziness, loss of balance or coordination</li> <li>Sudden severe headache with no known cause</li> </ul> <p>It is important to treat strokes as quickly as possible. <a href=\"https://medlineplus.gov/bloodthinners.html\">Blood thinners</a> may be used to stop a stroke while it is happening by quickly dissolving the blood clot. <a href=\"https://medlineplus.gov/strokerehabilitation.html\">Post-stroke rehabilitation</a> can help people overcome disabilities caused by stroke damage.</p> <p class=\"\">NIH: National Institute of Neurological Disorders and Stroke</p>",
      "sourceName": "MEDLINEPLUS"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "meaning": "Acute ischemic stroke (AIS) is defined by the sudden loss of blood flow to an area of the brain with the resulting loss of neurologic function. It is caused by thrombosis or embolism that occludes a cerebral vessel supplying a specific area of the brain. During a vessel occlusion, there is a core area where damage to the brain is irreversible and an area of penumbra where the brain has lost function owing to decreased blood flow but is not irreversibly injured. [PMID:32054610]",
      "sourceName": "HPO"
    }
  ],
  "synonyms": [
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "ischemic stroke",
      "sourceName": "CHV"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischemic Stroke",
      "sourceName": "MEDLINEPLUS"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Stroke, Ischaemic",
      "sourceName": "MSH"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Stroke, ischemic",
      "sourceName": "OMIM"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "stroke ischemic",
      "sourceName": "CHV"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Stroke, Ischemic",
      "sourceName": "MSH"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "STROKE, ISCHEMIC",
      "sourceName": "OMIM"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischemic Cerebrovascular Accident",
      "sourceName": "NCI"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischemic stroke",
      "sourceName": "HPO"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischemic stroke",
      "sourceName": "MTH"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischemic Stroke",
      "sourceName": "NCI"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischaemic Stroke",
      "sourceName": "MSH"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischaemic stroke",
      "sourceName": "HPO"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "ischaemic strokes",
      "sourceName": "CHV"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "ischaemic stroke",
      "sourceName": "CHV"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischemic Strokes",
      "sourceName": "MSH"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischaemic Strokes",
      "sourceName": "MSH"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "ischemic strokes",
      "sourceName": "CHV"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischemic stroke",
      "sourceName": "OMIM"
    },
    {
      "concept": {
        "cui": "C0948008",
        "preferredName": "Ischemic stroke"
      },
      "term": "Ischemic Stroke",
      "sourceName": "MSH"
    }
  ],
  "semanticTypes": [
    "Disease or Syndrome"
  ],
  "broaderConcepts": [],
  "narrowerConcepts": [
    {
      "cui": "C5392097",
      "preferredName": "Cryptogenic Ischemic Stroke"
    },
    {
      "cui": "C5392832",
      "preferredName": "Wake-up Stroke"
    },
    {
      "cui": "C5392833",
      "preferredName": "Acute Ischemic Stroke"
    }
  ]
}
----
====

==== Error Responses:
* Status Code: 404 (Not Found)
* Response Format: text/plain
* Example Response:
+
[source, text]
----
Could not found concept cui: <cui>
----

=== Search Concepts by Freetext

Search for concepts using the freetext.


* Endpoint: `/api/v1/concepts`
* Method: GET
* Parameters

[options="header"]
|==================
| Parameter | Type  | Required | Description
| queryText | string| Yes      | The freetext query string
|==================

* Example: http://localhost:8080/api/v1/concepts?queryText=root

==== Response:

* Status Code: 200 (OK)
* Response Format: JSON
* Example Response: "array of cui (search for concept by cui example)"

==== Error Responses:
* Status Code: 500 (Internal Server Error)
* Response Format: text/plain
* Example Response:
+
[source, text]
----
Error while processing freetext to cuis
----
